mvc_module:
    resource: "@MVCModuleBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

hello:
    path:         /info/
    defaults:     { _controller: MVCModuleBundle:Default:index }